
spring:
  application:
    name: gateway
  .
  cloud:
    consul:
      port: 8500
      host: localhost
    gateway:
      routes:
        - id: user_route
          uri: http://localhost:9900/
          predicates:
            - Path=/user/{state}
          filters:
            - SetPath=/{state}

server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: *
