---
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        -
          id: user_route
          predicates:
            - Path=/user/Checking
          uri: lb://UserService
      discovery:
        locator:
          enabled: true
