--- 
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
server: 
  port: 9000
spring: 
  application: 
    name: gateway
  cloud: 
    consul: 
      host: localhost
      port: 8500
    gateway: 
      routes: 
        - 
          filters: 
            - "SetPath=/{state}"
          id: user_route
          predicates: 
            - "Path=/user/{state}"
          uri: "http://localhost:9900/"
