--- 
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
server: 
  port: 9000
spring: 
  application: 
    name: gateway
  cloud: 
    consul: 
      host: localhost
      port: 8500
    gateway: 
      routes:
        -
          id: email_route
          predicates:
            - Path=/email/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:9950/"
        - id: user_route
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:9900/"
